/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // JMH plugin for benchmarking
    id("me.champeau.jmh") version "0.7.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // JMH dependencies for benchmarking
    jmhImplementation(libs.jmh.core)
    jmhAnnotationProcessor(libs.jmh.generator.annprocess)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("run.java.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// JMH configuration
val baselineDir = file("${rootProject.projectDir}/benchmark/baseline")
val jmhResultFile = file("${baselineDir}/jmh-result.json")
val jfrRecordingFile = file("${baselineDir}/profile.jfr")
val jfrEnabled = project.findProperty("jfrEnabled") == "true"
val benchmarkProfile = (project.findProperty("benchmarkProfile")?.toString() ?: "fast").lowercase()
val useFullProfile = benchmarkProfile == "full"
val baselineIncludesPattern = ".*(SortBenchmarks|PrimesBenchmarks|ControlBenchmarks).*"

jmh {
    warmupIterations.set(if (useFullProfile) 5 else 1)
    iterations.set(if (useFullProfile) 5 else 2)
    fork.set(1)
    threads.set(1)
    benchmarkMode.set(listOf("avgt"))
    timeUnit.set("ms")
    timeOnIteration.set(if (useFullProfile) "1s" else "300ms")
    resultFormat.set("json")
    // Baseline scope intentionally restricted to the 16-method suite.
    includes.set(listOf(baselineIncludesPattern))
}

// Runs baseline suite and persists the JMH JSON in benchmark/baseline.
tasks.register("jmhBaseline") {
    group = "benchmark"
    description = "Run baseline JMH benchmarks (fast default, full via -PbenchmarkProfile=full)"

    dependsOn("jmh")

    doLast {
        baselineDir.mkdirs()

        val jmhOutput = file("${project.layout.buildDirectory.get().asFile}/results/jmh/results.json")
        if (!jmhOutput.exists()) {
            throw GradleException("Expected JMH output missing at ${jmhOutput.absolutePath}")
        }
        jmhOutput.copyTo(jmhResultFile, overwrite = true)

        println("================================================================================")
        println("BASELINE BENCHMARK EXECUTION COMPLETED")
        println("================================================================================")
        println("Profile: ${if (useFullProfile) "full" else "fast"}")
        println("Includes pattern: $baselineIncludesPattern")
        println("Results file: ${jmhResultFile.absolutePath}")
        println("Results size: ${jmhResultFile.length()} bytes")
        if (jfrEnabled) {
            println("JFR flag requested. This task records JSON baseline only.")
            println("Use explicit JVM recording flags on app:jmh for controlled JFR capture.")
        }
        println("================================================================================")
    }
}
